package org.spl;

public enum State {
    START, IDENTIFIER, NUMERIC, BRACKET, PUNCTUATION, OPERATOR, ASSIGNMENT, LESS_THAN, GREATER_THAN,
    EXCLAMATION_MARK, MINUS, EQUAL, LESS_THAN_OR_EQUAL, GREATER_THAN_OR_EQUAL, NOT_EQUAL,
    AND, OR, SLASH, FIELD, AMPERSAND, BAR, STAR, ONE_LINE_COMMENT, MULTI_LINE_COMMENT, ERROR
}
