package org.spl;

public enum Symbol {
    LETTER, DIGIT, BRACKET, PUNCTUATION, STAR, PLUS, PERCENT, COLON, MINUS, EXCLAMATION_MARK, EQUAL_SIGN, SLASH,
    LESS_THAN, GREATER_THAN, AMPERSAND, BAR, UNDERSCORE, DOT, NEW_LINE, TAB, SPACE
}
