package org.spl.scanner;

public enum SingleCharacter {
    LETTER, DIGIT, BRACKET, PUNCTUATION, STAR, PLUS, PERCENT, COLON, MINUS, EXCLAMATION_MARK, EQUAL_SIGN, SLASH,
    LESS_THAN, GREATER_THAN, AMPERSAND, BAR, UNDERSCORE, DOT, APOSTROPHE, NEW_LINE, TAB, SPACE
}
